### ISSUE TITLE
ออกแบบปุ่มสำหรับUIหน้าเริ่มเกม

### ISSUE THREAD

**Issue by TeetatB** [TeetatB/ProjectGroup5#13]

**Comment by patiphan24** [comment]
![Uploading ไม่มีชื่อ 10_20230906121335.png…]()

**Comment by patiphan24** [comment]
![ไม่มีชื่อ 10_20230906121335](https://github.com/TeetatB/ProjectGroup5/assets/141816451/da72eb31-dfcb-437f-8389-49278032879a)

**Comment by patiphan24** [comment]
![ไม่มีชื่อ 11_20230906125217](https://github.com/TeetatB/ProjectGroup5/assets/141816451/deeb0178-364c-46e2-8fab-0c46247bff6b)

**Comment by patiphan24** [comment]
![ไม่มีชื่อ 12_20230906132305](https://github.com/TeetatB/ProjectGroup5/assets/141816451/1be3ab2e-0cdb-4e1b-bd6a-fe12f42f5955)

**Comment by patiphan24** [comment]
![ไม่มีชื่อ 13_20230906134000](https://github.com/TeetatB/ProjectGroup5/assets/141816451/8549568e-95bb-41ae-a0e3-c5d867e12d86)
