### ISSUE TITLE
Boss Monster

### ISSUE THREAD

**Issue by TeetatB** [TeetatB/ProjectGroup5#17]

**Comment by patiphan24** [comment]
![FPS2](https://github.com/TeetatB/ProjectGroup5/assets/141816451/f5248e18-4bdb-4028-a426-ab260eb03c9e)

**Comment by patiphan24** [comment]
![FPS3](https://github.com/TeetatB/ProjectGroup5/assets/141816451/9b603252-f468-4aa9-8c4d-c8ce0e017bc3)

**Comment by patiphan24** [comment]
![FPS4](https://github.com/TeetatB/ProjectGroup5/assets/141816451/16d3de43-1c94-42ef-9699-a6edcc13c1ee)

**Comment by patiphan24** [comment]
![FPS5](https://github.com/TeetatB/ProjectGroup5/assets/141816451/d1ea8ae8-f613-404e-9347-85bdd30ee6b4)

**Comment by patiphan24** [comment]
![FPS6](https://github.com/TeetatB/ProjectGroup5/assets/141816451/04cfa7ca-cd84-45a2-94e2-ce02aebcecd9)

**Comment by patiphan24** [comment]
![FPS7](https://github.com/TeetatB/ProjectGroup5/assets/141816451/0741737a-531e-45c4-ab7e-2a31ec6c5df6)

**Comment by patiphan24** [comment]
![FPS8](https://github.com/TeetatB/ProjectGroup5/assets/141816451/5f18dcf0-fd26-4a05-ac87-29eb36d6028c)

**Comment by patiphan24** [comment]
![FPS8](https://github.com/TeetatB/ProjectGroup5/assets/141816451/eef8e1c1-e094-4b77-a700-4d890a73ca7e)
