### ISSUE TITLE
ออกแบบตัวละครเอก

### ISSUE THREAD

**Issue by TeetatB** [TeetatB/ProjectGroup5#18]

**Comment by patiphan24** [comment]
![IMG_0460](https://github.com/TeetatB/ProjectGroup5/assets/141816451/7c1b211c-27f1-4333-b059-b829646ae208)

**Comment by patiphan24** [comment]
![IMG_0461](https://github.com/TeetatB/ProjectGroup5/assets/141816451/9fe85326-36ce-4fe7-bd16-2edf4493e495)

**Comment by patiphan24** [comment]
![ยิงบนใส่แมส](https://github.com/TeetatB/ProjectGroup5/assets/141816451/93c2f8f3-59d2-455b-bd27-f4c6c04cbef1)

**Comment by patiphan24** [comment]
![ยิงตรงใส่แมส](https://github.com/TeetatB/ProjectGroup5/assets/141816451/203da1c6-b860-46ad-9932-d37fae08d2ec)

**Comment by patiphan24** [comment]
![ยิงล่างใส่แมส](https://github.com/TeetatB/ProjectGroup5/assets/141816451/7f726b9f-b41f-43ee-8def-f5f19b528ce3)
