### ISSUE TITLE
แก้bugการแตะสี

### ISSUE THREAD

**Issue by TeetatB** [TeetatB/ProjectGroup5#21]

**Comment by Arthinan660610807** [comment]
เปลี่ยนจากการแตะสีนั้นๆด้วย repeat until แตะสีนั้น เป็น if เมื่อแตะสีนั้น แล้วครอบด้วย forever

**Comment by Arthinan660610807** [comment]
เปลี่ยนจากการแตะสีนั้นๆด้วย repeat until แตะสีนั้น เป็น if เมื่อแตะสีนั้น แล้วครอบด้วย forever
