### ISSUE TITLE
ออกแบบ Advance Monsters

### ISSUE THREAD

**Issue by TeetatB** [TeetatB/ProjectGroup5#22]

**Comment by patiphan24** [comment]
![1ซ้าย](https://github.com/TeetatB/ProjectGroup5/assets/141816451/d6eb3dae-a42f-4c92-8ade-992fa2d446bb)

**Comment by patiphan24** [comment]
![2ซ้าย](https://github.com/TeetatB/ProjectGroup5/assets/141816451/84193096-0ec2-437b-9d72-ba77bf910700)

**Comment by patiphan24** [comment]
![3ซ้าย](https://github.com/TeetatB/ProjectGroup5/assets/141816451/0dfc99d2-b068-4b41-a3a3-d6aeb25f7b86)

**Comment by patiphan24** [comment]
![Portal](https://github.com/TeetatB/ProjectGroup5/assets/141816451/61ff1525-98f8-406f-b511-78d7f44a2d30)
