### ISSUE TITLE
Effect ประกอบการต่อสู้

### ISSUE THREAD

**Issue by raffanids** [TeetatB/ProjectGroup5#27]

**Comment by patiphan24** [comment]
![IMG_0462](https://github.com/TeetatB/ProjectGroup5/assets/141816451/898a4425-1e97-4c32-977d-8cacb6ea072d)

**Comment by patiphan24** [comment]
![IMG_0464](https://github.com/TeetatB/ProjectGroup5/assets/141816451/b4bb3082-f78d-4493-aaef-f65b91800ef8)

**Comment by patiphan24** [comment]
![IMG_0465](https://github.com/TeetatB/ProjectGroup5/assets/141816451/794debe5-0279-458b-9880-c9e9599ab51c)

**Comment by patiphan24** [comment]
![IMG_0466](https://github.com/TeetatB/ProjectGroup5/assets/141816451/29e23ea2-2a43-493e-8ce9-cc05cdee6539)

**Comment by patiphan24** [comment]
![สเปรย์](https://github.com/TeetatB/ProjectGroup5/assets/141816451/d66a23b8-2569-418b-90a6-36e49d8ca908)

**Comment by patiphan24** [comment]
![IMG_0496 (1)](https://github.com/TeetatB/ProjectGroup5/assets/141816451/beb80533-f3f8-443a-8fee-c312cb6e5b40)

**Comment by patiphan24** [comment]
![Uploading ไม่มีชื่อ 10_20230906121335.png…]()

**Comment by patiphan24** [comment]
![ไม่มีชื่อ 10_20230906121335](https://github.com/TeetatB/ProjectGroup5/assets/141816451/7875a264-a283-4071-92b0-bfcbf15caf1d)

**Comment by patiphan24** [comment]
![Portal](https://github.com/TeetatB/ProjectGroup5/assets/141816451/10f213cf-0709-42e3-ae51-72df739d368a)
