### ISSUE TITLE
ถกหัวข้อโครงงาน

### ISSUE THREAD

**Issue by TeetatB** [TeetatB/ProjectGroup5#4]

**Comment by Arthinan660610807** [comment]
https://discord.gg/VDxmJVJA

**Comment by Arthinan660610807** [comment]
เป็นแนวเกมที่เข้าถึงคนทั่วไปได้ง่าย เกมเพลย์ไม่มีความซับซ้อนมากเกินไป กำหนดธีมและออกแบบเกมเพลย์ได้อย่าเป็นระบบ(ไม่ขัดกัน) ง่ายต่อการกำหนดระดับความยากง่ายของเกม

**Comment by Arthinan660610807** [comment]
เป็นแนวเกมที่เข้าถึงคนทั่วไปได้ง่าย เกมเพลย์ไม่มีความซับซ้อนมากเกินไป กำหนดธีมและออกแบบเกมเพลย์ได้อย่าเป็นระบบ(ไม่ขัดกัน) ง่ายต่อการกำหนดระดับความยากง่ายของเกม
