### ISSUE TITLE
แบ่งหน้าที่ในการทำงาน

### ISSUE THREAD

**Issue by TeetatB** [TeetatB/ProjectGroup5#5]

**Comment by raffanids** [comment]
โฮม : Programmer, Taster 
มิกซ์ : Programmer, Taster 
ซี : Graphicdesigner 
รัฟ : Manager, Graphicdesigner

**Comment by TeetatB** [comment]
โฮม: ทำแบบร่างเกมส่วนของการกดจังหวะบางส่วน
มิกซ์: ทำแบบร่างเกมส่วนinterfaceและhealth pointบางส่วน
ซี: ออกแบบตัวละครบางส่วน
รัฟ: ออกแบบพื้นหลังบางส่วน
