### ISSUE TITLE
เตรียมสไลด์นำเสนอโครงงาน

### ISSUE THREAD

**Issue by TeetatB** [TeetatB/ProjectGroup5#6]

**Comment by raffanids** [comment]
![image](https://github.com/TeetatB/ProjectGroup5/assets/134605328/1d30d934-4faa-4126-af27-8aa0eef65c2e)

**Comment by Arthinan660610807** [comment]
**https://scratch.mit.edu/projects/887164558**

**Comment by TeetatB** [comment]
https://scratch.mit.edu/projects/876829606 หน้าต่างเริ่มเกมและระบบพลังชีวิต(เบื้องต้น)

**Comment by Arthinan660610807** [comment]
https://www.canva.com/design/DAFs_pVXK5U/T-NrKRoOZ9a0Ijg6pqLvqA/edit?utm_content=DAFs_pVXK5U&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton
