### ISSUE TITLE
พิจรณาคำติชมที่ได้จากการนำเสนอและนำแก้ไขตามสมควร

### ISSUE THREAD

**Issue by Arthinan660610807** [TeetatB/ProjectGroup5#7]

**Comment by raffanids** [comment]
สิ่งที่อจ.แนะนำให้ควรไปปรับพัฒนาแก้ไข
- เค้าโครงของเกมยังดูไม่ค่อยออกว่าจะออกมาเป็นหน้าตายังไง ควรเริ่มทำหน้าเกมและ UI ได้แล้ว
- การแบ่งงานใน GitHub ไม่ละเอียดและดูฮ้วนเกินไป อยากให้แบ่งให้ละเอียดและมากกว่านี้
- รูปแบบของเกมที่เลือกสำหรับอจ. อจ.ยังคิดว่าดูง่ายเกินไปอาจเป็นเพราะยังไม่เห็นรูปแบบเกมที่จะทำจริงๆด้วยเลยทำให้ไม่สามารถให้คะแนนความยากและง่ายของเกมได้ แนะนำให้รีบเริ่มทำหน้าเกมถ้ามันง่ายจะได้ปรับเปลี่ยนได้ไวโดยไม่กระทบต่อหลายๆฝ่าย
