### ISSUE TITLE
เช็คความเรียบร้อยของฉากหลัง

### ISSUE THREAD

**Issue by Arthinan660610807** [TeetatB/ProjectGroup5#9]

**Comment by raffanids** [comment]
![Uploading หน้าตอนเล่นเกม อันที่ 2 draf1.jpg…]()

**Comment by raffanids** [comment]
![อันที่ 1 draf2](https://github.com/TeetatB/ProjectGroup5/assets/134605328/bdbf877f-c928-4ed7-8991-da87a15bfbb8)

**Comment by raffanids** [comment]
![อันที่-1-draf3](https://github.com/TeetatB/ProjectGroup5/assets/134605328/16d256b5-84bb-4426-b0b8-4ca72e970e68)
